"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-10-09 01:11:28.630706
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('site', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='member_role'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id')
    )
    op.create_table('sectors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('area_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('layout', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sector_id', sa.Uuid(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('op_status', sa.String(length=100), nullable=True),
    sa.Column('op_status_source', sa.String(length=200), nullable=True),
    sa.Column('op_status_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('op_status_set_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['op_status_set_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capture_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sector_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('uploading', 'completed', 'cancelled', name='batch_status'), nullable=False),
    sa.Column('expected_count', sa.Integer(), nullable=True),
    sa.Column('capture_date', sa.String(length=40), nullable=True),
    sa.Column('operating_condition', sa.String(length=300), nullable=True),
    sa.Column('device_notes', sa.String(length=300), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sector_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('queued', 'validating', 'reconstructing', 'converting', 'ready', 'failed', 'cancelling', 'cancelled', name='job_status'), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=True),
    sa.Column('stage_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile', sa.String(length=40), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('photo_ids', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_host', sa.String(length=200), nullable=True),
    sa.Column('worker_pid', sa.Integer(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector_id', 'idempotency_key', name='uq_job_idempotency')
    )
    op.create_table('job_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sector_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('source', sa.Enum('imported', 'reconstructed', 'demo', name='model_source'), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('coordinate_system', sa.String(length=200), nullable=False),
    sa.Column('alignment', sa.JSON(), nullable=False),
    sa.Column('alignment_source', sa.String(length=200), nullable=True),
    sa.Column('scale_state', sa.Enum('uncalibrated', 'calibrated_unverified', 'verified', name='scale_state'), nullable=False),
    sa.Column('scale_factor', sa.Float(), nullable=True),
    sa.Column('scale_method', sa.String(length=200), nullable=True),
    sa.Column('tolerance_abs_m', sa.Float(), nullable=True),
    sa.Column('tolerance_rel', sa.Float(), nullable=True),
    sa.Column('tolerance_purpose', sa.String(length=300), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector_id', 'number')
    )
    op.create_table('source_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('sector_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('accepted', 'rejected', 'duplicate', name='photo_status'), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('duplicate_of_id', sa.Uuid(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime', sa.String(length=50), nullable=True),
    sa.Column('original_path', sa.String(length=500), nullable=True),
    sa.Column('working_path', sa.String(length=500), nullable=True),
    sa.Column('thumb_path', sa.String(length=500), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('working_width', sa.Integer(), nullable=True),
    sa.Column('working_height', sa.Integer(), nullable=True),
    sa.Column('working_scale', sa.Float(), nullable=True),
    sa.Column('exif_orientation', sa.Integer(), nullable=True),
    sa.Column('camera', sa.JSON(), nullable=False),
    sa.Column('camera_group', sa.String(length=64), nullable=True),
    sa.Column('quality', sa.JSON(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('inclusion_log', sa.JSON(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['capture_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['source_photos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_photos_sha256'), 'source_photos', ['sha256'], unique=False)
    op.create_table('annotations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('position', sa.JSON(), nullable=False),
    sa.Column('normal', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calibration_references',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('point_a', sa.JSON(), nullable=False),
    sa.Column('point_b', sa.JSON(), nullable=False),
    sa.Column('real_distance', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('real_distance_m', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=False),
    sa.Column('endpoints_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_version_id', 'kind')
    )
    op.create_table('validation_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('point_a', sa.JSON(), nullable=False),
    sa.Column('point_b', sa.JSON(), nullable=False),
    sa.Column('real_distance', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('real_distance_m', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=False),
    sa.Column('endpoints_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sector_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('annotation_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('source_photo_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_photo_id'], ['source_photos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_links')
    op.drop_table('validation_checks')
    op.drop_table('model_artifacts')
    op.drop_table('calibration_references')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_source_photos_sha256'), table_name='source_photos')
    op.drop_table('source_photos')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_table('processing_jobs')
    op.drop_table('capture_batches')
    op.drop_table('assets')
    op.drop_table('sectors')
    op.drop_table('project_members')
    op.drop_table('projects')
    op.drop_table('api_tokens')
    op.drop_table('users')
    # ### end Alembic commands ###
